version: 2.1

##################################
##            Anchors           ##
##################################
maybe-configure-staging: &maybe-configure-staging
  when:
    condition:
      equal: [ staging, << pipeline.git.branch >> ]
    steps:
      run:
        name: Setup Staging Environment
        command: |
          echo "export CF_USERNAME=$CF_USERNAME_STAGING" >> $BASH_ENV
          echo "export CF_PASSWORD=$CF_PASSWORD_STAGING" >> $BASH_ENV
          echo "export CF_SPACE=staging" >> $BASH_ENV
          echo "export CF_APP=federalist-proxy-staging" >> $BASH_ENV
          echo "export CF_VARS_FILE=./.cloudgov/vars/staging.yml" >> $BASH_ENV

maybe-configure-production: &maybe-configure-production
  when:
    condition:
      equal: [ main, << pipeline.git.branch >> ]
    steps:
      run:
        name: Setup Production Environment
        command: |
          echo "export CF_USERNAME=$CF_USERNAME_PRODUCTION" >> $BASH_ENV
          echo "export CF_PASSWORD=$CF_PASSWORD_PRODUCTION" >> $BASH_ENV
          echo "export CF_SPACE=production" >> $BASH_ENV
          echo "export CF_APP=federalist-proxy" >> $BASH_ENV
          echo "export CF_VARS_FILE=./.cloudgov/vars/production.yml" >> $BASH_ENV

install-and-log-into-cloudgov: &install-and-log-into-cloudgov
  run:
    name: Install and log into CF
    command: |
      curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zx
      mv cf /usr/local/bin
      cf version
      cf api https://api.fr.cloud.gov
      cf login -u $CF_USERNAME -p $CF_PASSWORD -o gsa-18f-federalist -s $CF_SPACE

log-out-of-cloudgov: &log-out-of-cloudgov
  run:
    name: Log out from Cloud.gov
    command: cf logout


##################################
##             Jobs             ##
##################################
jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: docker-compose run --no-deps app npm install
      - run:
          name: Parse Config
          command: docker-compose run --no-deps app node ./bin/parse-conf.js          
      - run:
          name: Run Tests
          command: docker-compose run app npm test

  deploy:
    machine: true
    environment:
      CF_MANIFEST: ./.cloudgov/manifest.yml
    steps:
      - checkout
      - *maybe-configure-staging
      - *maybe-configure-production
      - *install-and-log-into-cloudgov
      - deploy:
          command: ./.cloudgov/deploy.sh
      - *log-out-of-cloudgov

  recycle:
    machine: true
    steps:
      - *maybe-configure-staging
      - *maybe-configure-production
      - *install-and-log-into-cloudgov
      - run:
          name: Recycle the application
          command: cf restage $CF_APP --strategy rolling
      - *log-out-of-cloudgov

##################################
##          Workflows           ##
##################################
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - staging
                - main
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - staging
                - main
    jobs:
      - recycle